/**
 * Unique 8-digit Off-Grid Phone Number System
 * Rule:
 * - Exactly 8 digits.
 * - First 4 digits are mandatory system prefix: 4116.
 * - Next 4 digits are uniquely generated by the system (never duplicate/similar).
 * - Each user only gets ONE permanent number and cannot generate another.
 * - All messages and calls require this number.
 */

export const SYSTEM_PHONE_PREFIX = '4116';
const STORAGE_KEY_MY_NUMBER = 'lora_user_phone_number_v2';
const STORAGE_KEY_ASSIGNED_NUMBERS = 'lora_assigned_peer_numbers_v2';
const STORAGE_KEY_SEQ_COUNTER = 'lora_phone_sequence_counter_v2';

/**
 * Formats 8-digit number as "4116 XXXX"
 */
export function formatPhoneNumber(num?: string | null): string {
  if (!num) return '';
  const clean = num.replace(/\D/g, '');
  if (clean.length === 8) {
    return `${clean.slice(0, 4)} ${clean.slice(4)}`;
  }
  if (clean.length === 9) {
    return `${clean.slice(0, 3)} ${clean.slice(3, 6)} ${clean.slice(6)}`;
  }
  if (clean.length === 12 && clean.startsWith('244')) {
    return `+244 ${clean.slice(3, 6)} ${clean.slice(6, 9)} ${clean.slice(9)}`;
  }
  return num;
}

/**
 * Strips all spaces, hyphens, and non-digits
 */
export function cleanPhoneNumber(num?: string | null): string {
  if (!num) return '';
  return num.replace(/\D/g, '');
}

/**
 * Validates if the number conforms to the mandatory 4116 XXXX 8-digit rule
 */
export function isValidPhoneNumber(num: string): boolean {
  const clean = cleanPhoneNumber(num);
  return clean.length === 8 && clean.startsWith(SYSTEM_PHONE_PREFIX);
}

/**
 * Synchronous local generation of the next unique sequential number:
 * Starts at 4116 0001, then 4116 0002, 4116 0003, etc.
 */
export function generateLocalSequentialNumber(): string {
  let counter = 1;
  try {
    const saved = localStorage.getItem(STORAGE_KEY_SEQ_COUNTER);
    if (saved) {
      const parsed = parseInt(saved, 10);
      if (!isNaN(parsed) && parsed >= 1) {
        counter = parsed;
      }
    }
  } catch {}

  const assigned = getAssignedNumbersMap();
  const assignedValues = new Set(Object.values(assigned));

  // Find next unused sequential number starting from counter
  while (assignedValues.has(`${SYSTEM_PHONE_PREFIX}${counter.toString().padStart(4, '0')}`)) {
    counter++;
  }

  const result = `${SYSTEM_PHONE_PREFIX}${counter.toString().padStart(4, '0')}`;
  
  try {
    localStorage.setItem(STORAGE_KEY_SEQ_COUNTER, (counter + 1).toString());
  } catch {}

  return result;
}

/**
 * Generate and assign permanent phone number for the user:
 * Synchronizes with server backend to guarantee no duplicates across multiple clients,
 * strictly starting at 4116 0001 and counting sequentially.
 */
export async function allocatePermanentUserNumber(nodeId: string): Promise<string> {
  if (typeof window === 'undefined') return '41160001';

  try {
    const existing = localStorage.getItem(STORAGE_KEY_MY_NUMBER);
    if (existing && isValidPhoneNumber(existing)) {
      return existing;
    }

    // Try server-authoritative allocation
    try {
      const resp = await fetch('/api/mesh/phone/allocate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ nodeId: nodeId || 'self_node' }),
      });

      if (resp.ok) {
        const data = await resp.json();
        if (data && data.phoneNumber && isValidPhoneNumber(data.phoneNumber)) {
          localStorage.setItem(STORAGE_KEY_MY_NUMBER, data.phoneNumber);
          return data.phoneNumber;
        }
      }
    } catch {
      // Offline fallback
    }

    // Local sequential allocation starting at 41160001
    const candidate = generateLocalSequentialNumber();
    localStorage.setItem(STORAGE_KEY_MY_NUMBER, candidate);
    return candidate;
  } catch {
    return '41160001';
  }
}

/**
 * Get or create the user's permanent 8-digit number.
 * "um usuario só tem direito a um, ela não pode gerar mais um outro"
 * O primeiro vai ser o usuario 4116 0001 e assim em seguida.
 */
export function getMyPermanentPhoneNumber(): string {
  if (typeof window === 'undefined') return '41160001';

  try {
    const existing = localStorage.getItem(STORAGE_KEY_MY_NUMBER);
    if (existing && isValidPhoneNumber(existing)) {
      return existing;
    }

    const candidate = generateLocalSequentialNumber();
    localStorage.setItem(STORAGE_KEY_MY_NUMBER, candidate);
    return candidate;
  } catch {
    return '41160001';
  }
}

export function setMyPermanentPhoneNumber(num: string): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY_MY_NUMBER, num);
  } catch {}
}

/**
 * Registry of assigned numbers for mesh nodes to prevent collisions
 */
function getAssignedNumbersMap(): Record<string, string> {
  if (typeof window === 'undefined') return {};
  try {
    const raw = localStorage.getItem(STORAGE_KEY_ASSIGNED_NUMBERS);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveAssignedNumbersMap(map: Record<string, string>): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY_ASSIGNED_NUMBERS, JSON.stringify(map));
  } catch {}
}

/**
 * Deterministically assigns or retrieves a unique 8-digit 4116-XXXX number for any node
 */
export function getNodePhoneNumber(nodeId: string, isSelf?: boolean): string {
  if (isSelf) {
    return getMyPermanentPhoneNumber();
  }

  if (nodeId === 'group-broadcast') {
    return '41160000'; // Broadcast channel number
  }

  if (nodeId.startsWith('node_phone_')) {
    return nodeId.replace('node_phone_', '');
  }

  const map = getAssignedNumbersMap();
  if (map[nodeId] && isValidPhoneNumber(map[nodeId])) {
    return map[nodeId];
  }

  // Generate unique suffix from hash of nodeId
  let hash = 0;
  for (let i = 0; i < nodeId.length; i++) {
    hash = (hash << 5) - hash + nodeId.charCodeAt(i);
    hash |= 0;
  }

  const baseNum = Math.abs(hash) % 9000 + 1000;
  let candidate = `${SYSTEM_PHONE_PREFIX}${baseNum.toString().padStart(4, '0')}`;

  // Ensure no duplicate with self or other nodes
  const myNum = getMyPermanentPhoneNumber();
  const existingValues = new Set([...Object.values(map), myNum]);

  let offset = 0;
  while (existingValues.has(candidate) && offset < 9000) {
    offset++;
    const nextVal = (baseNum + offset) % 9000 + 1000;
    candidate = `${SYSTEM_PHONE_PREFIX}${nextVal.toString().padStart(4, '0')}`;
  }

  map[nodeId] = candidate;
  saveAssignedNumbersMap(map);
  return candidate;
}
