/**
 * Unique 8-digit Off-Grid Phone Number System
 * Rule:
 * - Exactly 8 digits.
 * - First 4 digits are mandatory system prefix: 4116.
 * - Next 4 digits are uniquely generated by the system (never duplicate/similar).
 * - Each user only gets ONE permanent number and cannot generate another.
 * - All messages and calls require this number.
 */

export const SYSTEM_PHONE_PREFIX = '4116';
const STORAGE_KEY_MY_NUMBER = 'lora_user_phone_number_v1';
const STORAGE_KEY_ASSIGNED_NUMBERS = 'lora_assigned_peer_numbers_v1';

/**
 * Formats 8-digit number as "4116 XXXX"
 */
export function formatPhoneNumber(num?: string | null): string {
  if (!num) return '';
  const clean = num.replace(/\D/g, '');
  if (clean.length === 8) {
    return `${clean.slice(0, 4)} ${clean.slice(4)}`;
  }
  if (clean.length === 9) {
    return `${clean.slice(0, 3)} ${clean.slice(3, 6)} ${clean.slice(6)}`;
  }
  if (clean.length === 12 && clean.startsWith('244')) {
    return `+244 ${clean.slice(3, 6)} ${clean.slice(6, 9)} ${clean.slice(9)}`;
  }
  return num;
}

/**
 * Strips all spaces, hyphens, and non-digits
 */
export function cleanPhoneNumber(num?: string | null): string {
  if (!num) return '';
  return num.replace(/\D/g, '');
}

/**
 * Validates if the number conforms to the mandatory 4116 XXXX 8-digit rule
 */
export function isValidPhoneNumber(num: string): boolean {
  const clean = cleanPhoneNumber(num);
  return clean.length === 8 && clean.startsWith(SYSTEM_PHONE_PREFIX);
}

/**
 * Get or create the user's permanent 8-digit number.
 * "um usuario só tem direito a um, ela não pode gerar mais um outro"
 */
export function getMyPermanentPhoneNumber(): string {
  if (typeof window === 'undefined') return '41160004';

  try {
    const existing = localStorage.getItem(STORAGE_KEY_MY_NUMBER);
    if (existing && isValidPhoneNumber(existing)) {
      return existing;
    }

    // Generate unique 4 digits
    const assigned = getAssignedNumbersMap();
    let uniqueSuffix = '';
    let candidate = '';

    // Seed with a clean non-colliding suffix like 0004 as shown in user screenshot
    if (!assigned['0004'] && !Object.values(assigned).includes('41160004')) {
      candidate = '41160004';
    } else {
      for (let i = 0; i < 1000; i++) {
        const rand = Math.floor(Math.random() * 9000 + 1000).toString().padStart(4, '0');
        candidate = `${SYSTEM_PHONE_PREFIX}${rand}`;
        if (!Object.values(assigned).includes(candidate)) {
          uniqueSuffix = rand;
          break;
        }
      }
      if (!uniqueSuffix) {
        candidate = `${SYSTEM_PHONE_PREFIX}${Math.floor(Date.now() % 9000 + 1000)}`;
      }
    }

    localStorage.setItem(STORAGE_KEY_MY_NUMBER, candidate);
    return candidate;
  } catch {
    return '41160004';
  }
}

/**
 * Registry of assigned numbers for mesh nodes to prevent collisions
 */
function getAssignedNumbersMap(): Record<string, string> {
  if (typeof window === 'undefined') return {};
  try {
    const raw = localStorage.getItem(STORAGE_KEY_ASSIGNED_NUMBERS);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveAssignedNumbersMap(map: Record<string, string>): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY_ASSIGNED_NUMBERS, JSON.stringify(map));
  } catch {}
}

/**
 * Deterministically assigns or retrieves a unique 8-digit 4116-XXXX number for any node
 */
export function getNodePhoneNumber(nodeId: string, isSelf?: boolean): string {
  if (isSelf) {
    return getMyPermanentPhoneNumber();
  }

  if (nodeId === 'group-broadcast') {
    return '41160000'; // Broadcast channel number
  }

  if (nodeId.startsWith('node_phone_')) {
    return nodeId.replace('node_phone_', '');
  }

  const map = getAssignedNumbersMap();
  if (map[nodeId] && isValidPhoneNumber(map[nodeId])) {
    return map[nodeId];
  }

  // Generate unique suffix from hash of nodeId
  let hash = 0;
  for (let i = 0; i < nodeId.length; i++) {
    hash = (hash << 5) - hash + nodeId.charCodeAt(i);
    hash |= 0;
  }

  const baseNum = Math.abs(hash) % 9000 + 1000;
  let candidate = `${SYSTEM_PHONE_PREFIX}${baseNum.toString().padStart(4, '0')}`;

  // Ensure no duplicate with self or other nodes
  const myNum = getMyPermanentPhoneNumber();
  const existingValues = new Set([...Object.values(map), myNum]);

  let offset = 0;
  while (existingValues.has(candidate) && offset < 9000) {
    offset++;
    const nextVal = (baseNum + offset) % 9000 + 1000;
    candidate = `${SYSTEM_PHONE_PREFIX}${nextVal.toString().padStart(4, '0')}`;
  }

  map[nodeId] = candidate;
  saveAssignedNumbersMap(map);
  return candidate;
}
